### ISSUE TITLE
Can you release a version ?

### ISSUE THREAD

**Issue by GeoloeG-IsT** [akc42/akc-meta#1]
Hi, 
nice job, it works indeed perfectly and now I understand why you did it!
(we quickly exchange on SO)
So can you gently release a version so that we can reference it via bower?
Thanks one more!
Pascal

**Comment by GeoloeG-IsT** [comment]
@JeremybellEU

**Comment by TimvdLippe** [comment]
:+1:

**Comment by akc42** [comment]
Done

**Comment by GeoloeG-IsT** [comment]
Thanks! :)
