### ISSUE TITLE
can you use semver v1.0.0 ? ;)

### ISSUE THREAD

**Issue by GeoloeG-IsT** [akc42/akc-meta#2]
Thx! :)

**Comment by GeoloeG-IsT** [comment]
and if you want a use-case, check the current demo here:
https://metanov.github.io/firebase-element-extended/
cheers,
Pascal

**Comment by akc42** [comment]
Does this help

**Comment by GeoloeG-IsT** [comment]
just to be consistent with the current semver scheme accross component, up to you! :)

**Comment by akc42** [comment]
I've done it anyway.  its the same state as the one I marked as v1.0.

**Comment by GeoloeG-IsT** [comment]
thx again!
