### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by JGSolutions** [akc42/akc-meta#4]
Can we install this through bower? I tried bower install akc-meta and cannot not find it.

Thanks in advance

**Comment by akc42** [comment]
Just put an entry like this in your bower.json file under dependancies.

`"akc-meta": "akc42/akc-meta",`

I haven't registered with any bower registry as I don't really know how, but the above line works for me - bower just pulls it in from github.

**Comment by JGSolutions** [comment]
cool thanks it works :)

i did a bower search akc-meta and didn't find it.
